[package]
name = "cli-program-template"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
borsh = "0.9.0"
clap = "2.33.3"
lazy_static = "1.4.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_yaml = "0.8.17"
sol-template-shared = {path = "shared"}
solana-clap-utils = "=1.7.8"
solana-cli-config = "=1.7.8"
solana-client = "=1.7.8"
solana-logger = "=1.7.8"
solana-remote-wallet = "=1.7.8"
solana-sdk = "=1.7.8"
tokio = { version = "1", features = ["full"] }

[workspace]
members = [
    "program",
    "shared",
]
[dev-dependencies]
lazy_static = "1.4.0"
solana-validator = "=1.7.8"
