[package]
name = "cli-template"
version = "0.1.0"
edition = "2018"
license = "WTFPL"
publish = false

[dependencies]
clap = "2.33.3"
lazy_static = "1.4.0"
serde = { version = "1.0.125", features = ["derive"] }
serde_yaml = "0.8.17"
solana-clap-utils = "=1.7.0"
solana-cli-config = "=1.7.0"
solana-client = "=1.7.0"
solana-logger = "=1.7.0"
solana-remote-wallet = "=1.7.0"
solana-sdk = "=1.7.0"
tokio = { version = "1", features = ["full"] }

[workspace]
exclude = ["program"]

[dev-dependencies]
lazy_static = "1.4.0"
solana-validator = "=1.7.0"
